"""
api/config_writer.py — Generate config.toml files for pipeline runs.

Writes a complete config.toml (Prowler) or scubagear_config.toml (ScubaGear)
from the engagement and run parameters. The pipelines are never modified —
all per-run customisation goes through the config file.
"""

from __future__ import annotations

import re
from pathlib import Path

_PROWLER_TEMPLATE = """\
# config.toml generated by Cloud Security Reporter GUI

[engagement]
client_name       = {client_name!r}
assessment_period = {assessment_period!r}
analyst           = {analyst!r}
output_filename   = {output_filename!r}

[llm]
provider         = "bedrock_runtime"
deployment_name  = {deployment_name!r}
aws_region       = {aws_region!r}
max_tokens       = 1500
timeout_seconds  = 60

[processing]
include_statuses = ["FAIL", "MUTED(FAIL)"]
preserve_passing = false

[severity_rules]
critical      = "High"
high          = "High"
medium        = "Medium"
low           = "Low"
informational = "Low"

likelihood_high_if_categories = ["internet-exposed"]

[risk_matrix]
High_Major      = "High"
High_Moderate   = "High"
High_Minor      = "High"
Medium_Major    = "High"
Medium_Moderate = "Medium"
Medium_Minor    = "Medium"
Low_Major       = "Medium"
Low_Moderate    = "Medium"
Low_Minor       = "Low"

[output]
template_path = {template_path!r}
ref_prefix    = "AWS"

[output.colours]
High   = "FFFF0000"
Medium = "FFFFC000"
Low    = "FF92D050"
"""

_SCUBAGEAR_TEMPLATE = """\
# scubagear_config.toml generated by Cloud Security Reporter GUI

[engagement]
client_name       = {client_name!r}
assessment_period = {assessment_period!r}
analyst           = {analyst!r}
tenant_id         = {tenant_id!r}
output_filename   = {output_filename!r}

[llm]
provider         = "bedrock_runtime"
deployment_name  = {deployment_name!r}
aws_region       = {aws_region!r}
max_tokens       = 1500
timeout_seconds  = 60

[processing]
include_criticality = ["Shall", "Shall/3rd Party", "Shall/Not Implemented"]

[severity_map]
"Shall"                 = "high"
"Shall/3rd Party"       = "high"
"Shall/Not Implemented" = "high"
"Should"                = "medium"
"May"                   = "low"

[service_map]
"MS.AAD"           = {{ section = "Microsoft Entra ID",            ref_prefix = "ENT" }}
"MS.DEFENDER"      = {{ section = "Microsoft 365 Defender",        ref_prefix = "DEF" }}
"MS.EXO"           = {{ section = "Microsoft Exchange Online",     ref_prefix = "EXO" }}
"MS.SHAREPOINT"    = {{ section = "Microsoft SharePoint Online",   ref_prefix = "SPO" }}
"MS.TEAMS"         = {{ section = "Microsoft Teams",               ref_prefix = "TEA" }}
"MS.POWERPLATFORM" = {{ section = "Microsoft Power Platform",      ref_prefix = "PWR" }}

[risk_matrix]
High_Major      = "High"
High_Moderate   = "High"
High_Minor      = "High"
Medium_Major    = "High"
Medium_Moderate = "Medium"
Medium_Minor    = "Medium"
Low_Major       = "Medium"
Low_Moderate    = "Medium"
Low_Minor       = "Low"

[output]
template_path = {template_path!r}
target_sheet  = "Azure"

[output.colours]
High   = "FFFF0000"
Medium = "FFFFC000"
Low    = "FF92D050"
"""


def _safe_filename(name: str) -> str:
    name = name.strip()
    name = re.sub(r"[^\w\s\-]", "", name)
    name = re.sub(r"[\s]+", "_", name)
    return name or "client"


def write_prowler_config(
    output_dir: Path,
    client_name: str,
    assessment_period: str,
    analyst: str,
    aws_region: str,
    template_path: str,
    deployment_name: str = "",
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "config.toml"
    output_filename = f"SecurityReport_{_safe_filename(client_name)}.xlsx"
    content = _PROWLER_TEMPLATE.format(
        client_name=client_name,
        assessment_period=assessment_period,
        analyst=analyst,
        aws_region=aws_region,
        output_filename=output_filename,
        template_path=template_path,
        deployment_name=deployment_name,
    )
    config_path.write_text(content, encoding="utf-8")
    return config_path


def write_scubagear_config(
    output_dir: Path,
    client_name: str,
    assessment_period: str,
    analyst: str,
    aws_region: str,
    tenant_id: str,
    template_path: str,
    deployment_name: str = "",
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "scubagear_config.toml"
    output_filename = f"M365_SecurityReport_{_safe_filename(client_name)}.xlsx"
    content = _SCUBAGEAR_TEMPLATE.format(
        client_name=client_name,
        assessment_period=assessment_period,
        analyst=analyst,
        aws_region=aws_region,
        tenant_id=tenant_id,
        output_filename=output_filename,
        template_path=template_path,
        deployment_name=deployment_name,
    )
    config_path.write_text(content, encoding="utf-8")
    return config_path